### ISSUE TITLE
Error with python building on Ubuntu

### ISSUE THREAD

**Issue by Serjio42** [Li-Zhaoxi/AAMED#19]
Hi. I am trying to build the python package but facing the following error, could you please help to avoid it? I use `cython 3.0.10` and `python 3.10.13`.
```
AAMED-master/python$ python setup.py build_ext --inplace
running build_ext
Compiling pyAAMED.pyx because it changed.
[1/1] Cythonizing pyAAMED.pyx
/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /home/ubunter/Downloads/AAMED-master/python/pyAAMED.pyx
  tree = Parsing.p_module(s, pxd, full_module_name)

Error compiling Cython file:
------------------------------------------------------------
...
cdef class pyAAMED:
    cdef FLED* _fled;
    cdef int drows;
    cdef int dcols;
    def __cinit__(self, int drows, int dcols):
        self._fled = new FLED(drows, dcols)
                     ^
------------------------------------------------------------

pyAAMED.pyx:20:21: Operation only allowed in c++

Error compiling Cython file:
------------------------------------------------------------
...



    def release(self):
        #self._fled.release()
        del self._fled
        ^
------------------------------------------------------------

pyAAMED.pyx:42:8: Operation only allowed in c++
Traceback (most recent call last):
  File "/home/ubunter/Downloads/AAMED-master/python/setup.py", line 127, in <module>
    setup(
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/__init__.py", line 107, in setup
    return distutils.core.setup(**attrs)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 185, in setup
    return run_commands(dist)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/core.py", line 201, in run_commands
    dist.run_commands()
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 969, in run_commands
    self.run_command(cmd)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/dist.py", line 1234, in run_command
    super().run_command(command)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/dist.py", line 988, in run_command
    cmd_obj.run()
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 345, in run
    self.build_extensions()
  File "/home/ubunter/Downloads/AAMED-master/python/setup.py", line 124, in build_extensions
    build_ext.build_extensions(self)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 467, in build_extensions
    self._build_extensions_serial()
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/setuptools/_distutils/command/build_ext.py", line 493, in _build_extensions_serial
    self.build_extension(ext)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/Cython/Distutils/build_ext.py", line 130, in build_extension
    new_ext = cythonize(
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1154, in cythonize
    cythonize_one(*args)
  File "/home/ubunter/miniconda3/envs/playground310/lib/python3.10/site-packages/Cython/Build/Dependencies.py", line 1321, in cythonize_one
    raise CompileError(None, pyx_file)
Cython.Compiler.Errors.CompileError: pyAAMED.pyx

```

**Comment by kanstancin** [comment]
Hey, seems like in one of the recent versions of `cython` they no longer recognize "C++" in the `language` argument. Instead, it should be lower case "c++" now. In `python/setup.py` changing `language` to "c++" fixes the issue.
